// <auto-generated />
using System;
using Maintain.NET.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Maintain.NET.Migrations
{
    [DbContext(typeof(MaintainDbContext))]
    [Migration("20190314162708_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Maintain.NET.Models.MaintenanceTask", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("MaximumInterval");

                    b.Property<long>("MinimumInterval");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<long>("RecommendedInterval");

                    b.HasKey("ID");

                    b.ToTable("MaintenanceTasks");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            MaximumInterval = 10000L,
                            MinimumInterval = 2L,
                            Name = "Fish Tank",
                            RecommendedInterval = 1000L
                        },
                        new
                        {
                            ID = 2,
                            MaximumInterval = 10000L,
                            MinimumInterval = 2L,
                            Name = "Oil Change",
                            RecommendedInterval = 1000L
                        });
                });

            modelBuilder.Entity("Maintain.NET.Models.UserMaintenanceHistory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Interval");

                    b.Property<int>("MaintenanceRef");

                    b.Property<DateTime>("TimeComplete");

                    b.Property<string>("UserID");

                    b.Property<int>("UserMaintenanceTaskID");

                    b.Property<int>("UserMaintenanceTaskMaintenanceTaskID");

                    b.Property<string>("UserMaintenanceTaskUserID")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("UserMaintenanceTaskMaintenanceTaskID", "UserMaintenanceTaskUserID");

                    b.ToTable("UserMaintenanceHistories");
                });

            modelBuilder.Entity("Maintain.NET.Models.UserMaintenanceTask", b =>
                {
                    b.Property<int>("MaintenanceTaskID");

                    b.Property<string>("UserID");

                    b.Property<int>("ID");

                    b.Property<long>("LastComplete");

                    b.Property<long>("NextComplete");

                    b.HasKey("MaintenanceTaskID", "UserID");

                    b.ToTable("UserMaintenanceTasks");
                });

            modelBuilder.Entity("Maintain.NET.Models.UserMaintenanceHistory", b =>
                {
                    b.HasOne("Maintain.NET.Models.UserMaintenanceTask", "UserMaintenanceTask")
                        .WithMany("UserMaintenanceHistory")
                        .HasForeignKey("UserMaintenanceTaskMaintenanceTaskID", "UserMaintenanceTaskUserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Maintain.NET.Models.UserMaintenanceTask", b =>
                {
                    b.HasOne("Maintain.NET.Models.MaintenanceTask", "MaintenanceTask")
                        .WithMany("UserMaintenanceTasks")
                        .HasForeignKey("MaintenanceTaskID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
