// <auto-generated />
using System;
using Maintain.NET.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Maintain.NET.Migrations.MaintainDb
{
    [DbContext(typeof(MaintainDbContext))]
    [Migration("20190312212514_controllertest")]
    partial class controllertest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Maintain.NET.Models.MaintenanceTask", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("RecommendedInterval");

                    b.HasKey("ID");

                    b.ToTable("MaintenanceTasks");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Fish Tank",
                            RecommendedInterval = 2
                        },
                        new
                        {
                            ID = 2,
                            Name = "Oil Change",
                            RecommendedInterval = 4
                        });
                });

            modelBuilder.Entity("Maintain.NET.Models.UserMaintenanceHistory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("TimeComplete");

                    b.Property<string>("UserID");

                    b.Property<int>("UserMaintenanceTaskID");

                    b.HasKey("ID");

                    b.HasIndex("UserMaintenanceTaskID");

                    b.ToTable("UserMaintenanceHistories");
                });

            modelBuilder.Entity("Maintain.NET.Models.UserMaintenanceTask", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LastComplete");

                    b.Property<int>("MaintenanceTaskID");

                    b.Property<int>("NextComplete");

                    b.Property<string>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("MaintenanceTaskID");

                    b.ToTable("UserMaintenanceTasks");
                });

            modelBuilder.Entity("Maintain.NET.Models.UserMaintenanceHistory", b =>
                {
                    b.HasOne("Maintain.NET.Models.UserMaintenanceTask", "UserMaintenanceTask")
                        .WithMany("UserMaintenanceHistory")
                        .HasForeignKey("UserMaintenanceTaskID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Maintain.NET.Models.UserMaintenanceTask", b =>
                {
                    b.HasOne("Maintain.NET.Models.MaintenanceTask", "MaintenanceTask")
                        .WithMany("UserMaintenanceTasks")
                        .HasForeignKey("MaintenanceTaskID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
